name: notebooks-voila
channels:
  - conda-forge
dependencies:
  - python=3.12
  - voila
  - ipywidgets
  - nbformat
  - pandas
  - seaborn
  - matplotlib
  - scipy
  - numpy
  - sympy
  - ipykernel
  - ipympl
  - jupyter

