#!/bin/bash
set -x

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

REQUIREMENTS="${SCRIPT_DIR}/requirements.txt"
# Name of the virtual environment folder
VENV_DIR="$SCRIPT_DIR/venv"

if [ "$1" == "-d" ];
then
    rm -rf "$VENV_DIR"
fi

which python3
python3 --version

# Check if virtual environment directory already exists
if [ -d "$VENV_DIR" ]; then
    echo "Virtual environment already exists."
else
    # Create a virtual environment
    python3 -m venv "$VENV_DIR"
    echo "Virtual environment created."
fi

# Activate the virtual environment
source "$VENV_DIR/bin/activate"
echo "Virtual environment activated."

# Install dependencies from requirements.txt if the file exists
if [ -f "${REQUIREMENTS}" ]; then
    pip install --upgrade pip
    pip install -r "${REQUIREMENTS}"
    echo "Dependencies installed from requirements.txt."
else
    echo "requirements.txt not found. Skipping dependency installation."
fi


# REgister as a Jupyter kernel
python3 -m ipykernel install --user --name=ODE_env --display-name "ODE course Environment"
